### PR TITLE
Add systemd service guide to readme.md

### PR DESCRIPTION
**Pull request by lavaground**
Added a step-by-step guide for running the bot as a systemd service.

### CODE REVIEW

**Comment by lavaground** [comment]
This time using current readme.md 🙈

**Comment by getsec** [comment]
@lavaground  thanks - gonna put this in wiki instead.

**Comment by getsec** [comment]
https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/wiki/systemd-configuration

**Comment by lavaground** [comment]
Perfect, thanks.

**Pull request closed without merging**
