### PR TITLE
Code Refractoring

### PR DESCRIPTION
**Pull request by Anu-bhav**
I've made it more modularised and refactored certain parts.
It will now be easier to create custom signal modifiers.
It is not complete yet, there are some other parts that needs to be refactored.
The testnet feature is added again but it will only work if it is enabled in the config file.
The creds file is also modified to store both testnet and mainnet keys. 

The test_mode feature remained unchanged and it is not affected by testnet.

### CODE REVIEW

**Comment by ShogunMan** [comment]
Well we are for sure not going back to the testnet with it's limited pairs and keys, but staying with testmode.
Otherwise putting some stuff in helpers is ok.

**Comment by getsec** [comment]
Jesus this is a huge one

**Comment by ShogunMan** [comment]
> Jesus this is a huge one

Thats what my wife said.

**Comment by Anu-bhav** [comment]
@ShogunMan 
Ah the testnet one was only to test some functionalities. 
I've never used some of the libraries in this project so I was learning what can be done with it. 
If you want you can remove it from the config file and just put ```data["TESTNET"] = False``` in get_config.py.
It won't any impact anywhere else, you can also remove the test part in the creds file.

image

image

image

image

I've modified this in all the signalling modules, will do a PR later.

image

image


@getsec I plan on merging your mongo db PR in it, btw I'm pr0t0typ3 in discord. 

Can someone explain the pausebotmod to me?
Like I know it's suposed to check if the market is dry, but why the hardcoded value? Is it dependant on btc?

**Comment by Anu-bhav** [comment]
Yeah I forgot to mention, 
https://python-tradingview-ta.readthedocs.io/en/latest/usage.html
There's support for retrieving multiple analysis as from yesterday. 

However when I was not able to get the latest version with pip install, I had to manually install it.

It can be done as shown below, however I commented it for now. 
image

image
It can be used in signalling modules to drop the number of requests made.

**Comment by ShogunMan** [comment]
I think its too invasive on the current codebase. The multiple analysis has been implemented some time ago in my fork.
You could keep developing this version in your fork, but i don't see a full push of this.

**Comment by Anu-bhav** [comment]
Ok no problem I'll close the PR

**Pull request closed without merging**
