### PR TITLE
Adds a script that sells the remaining coins and deletes coins_bought file

### PR DESCRIPTION
**Pull request by Tarantinooo**

### CODE REVIEW

**Comment by Geeks-Sid** [comment]
Is this necessary? Shouldn't the trades be saved?

**Comment by Tarantinooo** [comment]
> Is this necessary? Shouldn't the trades be saved?

This is only for after you stop the script, and there are still coins left in your portfolio that the bot didn't sell yet. Instead of going to Binance and doing it manually, this script sells all the coins that are still left on the coins_bought list automatically

**Comment by Tarantinooo** [comment]
> Is this necessary? Shouldn't the trades be saved?

Also the trades are saved in another txt file, trades.txt

**Comment by ShogunMan** [comment]
I might not get it, but i can see that the script loads the coins, the deletes the json file. But where in the code does it actually sell the coins? I cant find any order creation.

**Comment by ShogunMan** [comment]
> > Is this necessary? Shouldn't the trades be saved?
> 
> Also the trades are saved in another txt file, trades.txt

But you are not writing the trades from this module into trades.txt, messing up the integrity of the file.
You will have coins that are bough, but never sold, and not know at what price or profit they were sold.

**Comment by Tarantinooo** [comment]
> > > Is this necessary? Shouldn't the trades be saved?
> > 
> > 
> > Also the trades are saved in another txt file, trades.txt
> 
> But you are not writing the trades from this module into trades.txt, messing up the integrity of the file.
> You will have coins that are bough, but never sold, and not know at what price or profit they were sold.

That's a good one. Didn't think of that. I will try to write something for that so that it still calculates it for the trades.txt file. Can't promise anything as I'm a beginner coder

**Pull request closed without merging**
