### PR TITLE
transform to modular design

### PR DESCRIPTION
**Pull request by CyberPunkMetalHead**

### CODE REVIEW

**Comment by O-Mutt** [comment]
I'm gonna echo a little bit from ☝️ 

This is less of a modular design and more of a function split. 

I would love to see a `portfolio.py` that handles all the CRUD of the portfolio, `binance_service` that handles interactions (and error handling) of external calls to the service. And break it down into responsibility rather than files.

**Comment by getsec** [comment]
@O-Mutt  and @Davidobot are right. Im gonna take a stab at this.

**Comment by CyberPunkMetalHead** [comment]
Fair enough. In that case I will close this request and merge @Davidobot ’s PR next. My only comment on your PR is that we could use a bit more logging when coins are not being bought, I thought the code was broken when it wouldn’t print anything for minutes at a time.

**Comment by CyberPunkMetalHead** [comment]
@getsec might wanna base it off David’s pr to avoid conflicts

**Comment by getsec** [comment]
> Fair enough. In that case I will close this request and merge @Davidobot ’s PR next. My only comment on your PR is that we could use a bit more logging when coins are not being bought, I thought the code was broken when it wouldn’t print anything for minutes at a time.

I think this is good. Once his PR is out we can expand.

**Pull request closed without merging**
