### PR TITLE
Introduces testnet configuration section 

### PR DESCRIPTION
**Pull request by NiklasLehnfeld**
Just started using this bot and on first try I didn't figured out how to work with the testnet. I was not able to connect to the testnet using my testnet API-Keys without making these changes. I really don't know how you worked with the bot on the testnet before. Let me know if my changes are okay or if there is a different way. But at least updating the python-binance dependency should be a good change.

### CODE REVIEW

**Comment by ShogunMan** [comment]
We removed testnet and its API keys, and are using just mainnet even for testing. We will not revert back to old version with the limited test net.

**Comment by NiklasLehnfeld** [comment]
Okay, didn't know that. Would be nice to have an updated documentation for that.

**Comment by ShogunMan** [comment]
I don't see anything in the current docs that references test net or its API keys. 
Maybe you could point it out to me so that we can correct it accordingly.

**Comment by piscui** [comment]
@ShogunMan I started trying the bot yesterday and was also confused about my testnet key not working.

There are still mentions of it in (at least) the main [README.md](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/blob/main/README.md#description) and the [FAQs](https://github.com/CyberPunkMetalHead/Binance-volatility-trading-bot/blob/main/FAQ.md).

The first link even has a link to [the original blog post](https://www.cryptomaton.org/2021/05/08/how-to-code-a-binance-trading-bot-that-detects-the-most-volatile-coins-on-binance/) (which is how I ended up here) where it talks in detail how to set up testnet.

So yeah, it can be confusing and I tend to agree with @NiklasLehnfeld that perhaps a mention of testnet being unsupported would be beneficial (and I also agree based on past experience that it can be a pain in the rear end to work with, so I'm not surprised you guys removed it).

Hope that helps.

**Comment by ShogunMan** [comment]
Thank, removed it now i hope :-)

**Comment by NiklasLehnfeld** [comment]
Thanks @piscui for the explanation, that is exactly what I meant. And thanks @ShogunMan for the removal. Can only agree. Great work with this tool!

**Pull request closed without merging**
