### PR TITLE
Adding ability to use dotenv

### PR DESCRIPTION
**Pull request by O-Mutt**
Ref #2 allows the user to add a .env file with their API key/secret (Also gives an `.env.example`)

### CODE REVIEW

**Review by lodenrogue — APPROVED** [review]

**Comment by mehdichaouch** [comment]
Also move the `TESTNET = False` in your `.env`

**Comment by mehdichaouch** [comment]
Why did you close this PR?

**Comment by O-Mutt** [comment]
There is another dev that is working on a similar fix to incorporate json/yaml file configuration that should fit a bit better.

**Comment by mehdichaouch** [comment]
@O-Mutt oh very good, when closing PR just put the new PR id for helping ;)

**Comment by O-Mutt** [comment]
#70

**Pull request closed without merging**
