### PR TITLE
porfolio -> portfolio

### PR DESCRIPTION
**Pull request by dopey**

### CODE REVIEW

**Review by lodenrogue — APPROVED** [review]

**Review by aeickmeyer — APPROVED** [review]

**Comment by ivandardi** [comment]
Already fixed by PR #64

**Comment by getsec** [comment]
Already fixed by PR #64

**Comment by lodenrogue** [comment]
You know what's really cool? Merging another person's PR with these changes when this one came first

**Comment by dopey** [comment]
Alas, I'll never get credit for my incredible spell-check commit 😞 . Seriously though, I don't mind :]

**Comment by lodenrogue** [comment]
I'm just busting balls man. No worries

**Pull request closed without merging**
