### PR TITLE
add custom exception message for timeout

### PR DESCRIPTION
**Pull request by getsec**

### CODE REVIEW

**Comment by getsec** [comment]
image
Example of what errors look like now

**Comment by Amraki** [comment]
The TLD isn't a configurable option yet, right?

With my limited python knowledge, I would submit a PR adding it but it probably isn't recommended to have so many edits for the same bit of code.
And it may be a debatable topic, but I'd be inclined to add the option to creds.yml instead of config.yml.

**Comment by Amraki** [comment]
Nevermind. Appears to be handled in #120

**Comment by VirtualMe64** [comment]
> Nevermind. Appears to be handled in #120

Yep, it should make it work for Binance US at least

**Review by CyberPunkMetalHead — APPROVED** [review]

**Pull request merged**
