### PR TITLE
Update Binance Detect Moonings.py

### PR DESCRIPTION
**Pull request by Balduxnet**

### CODE REVIEW

**Comment by ShogunMan** [comment]
And what does this update do?

**Comment by ShogunMan** [comment]
No answer, and does not seem to do anything useful.

**Comment by Balduxnet** [comment]
limit the number of exchanges to the desired ones

**Comment by ShogunMan** [comment]
I don't get it. 
We only support 1 exchange, Binance.
What is this code trying to do? Max_Coins already limits the concurrent number of orders.

**Pull request closed without merging**
