### PR TITLE
Alphabetized ticker list

### PR DESCRIPTION
**Pull request by kpaje**

### CODE REVIEW

**Comment by getsec** [comment]
Can i ask the reasoning behind this one?

**Comment by kpaje** [comment]
It's nice quickly knowing what is already on the list

**Comment by ShogunMan** [comment]
Import in excel > sort > save. Done.

**Comment by getsec** [comment]
@ShogunMan  Literally lol

```sh
❯ sort tickers.txt | head
1INCH
AAVE
ADA
ALGO
ALPHA
ANKR
ATOM
AVAX
BAKE
BAL

```

**Pull request merged**
