### PR TITLE
Added config based support for binance.us

### PR DESCRIPTION
**Pull request by VirtualMe64**
Adds list of USDT compatible tickers for Binance.US and a config parameter for users on the platform.

### CODE REVIEW

**Comment by CyberPunkMetalHead** [comment]
@O-Mutt what do you think about having the notifications in their own functions for simplicity?

**Comment by VirtualMe64** [comment]
> notifications

I think you meant to comment on #117?

**Comment by b225ccc** [comment]
These changes worked for me on binance.us - thanks @VirtualMe64!

**Comment by O-Mutt** [comment]
> > notifications
> 
> I think you meant to comment on #117?

That seems like what he meant 😄

**Comment by ShogunMan** [comment]
Implemented in latest ver.

**Pull request closed without merging**
